<?php

use Application\Controller\Terrain\CategorieStageController;
use Application\Form\Misc\ImportForm;
use Application\Service\Misc\CSVService;
use Application\Validator\Import\CategorieStageCsvImportValidator;
use UnicaenApp\View\Helper\Messenger;

/**
 * @see CategorieStageController::importerAction()
 * @var string $title
 * @var ImportForm $form
 */
$fe = $this->formErrors();
$fr = $this->formrow();
$fcg = $this->formControlGroup();
?>


<div class="card card-primary">
    <h1 class="page-header card-header">
        <span class="icon icon-importer"></span>
        <?= $title ?>
    </h1>
    <div class="card-body">
        <div class="fieldset">
            <?= $this->form()->openTag($form->prepare()) ?>
            <?= $fe($form->prepare(), $form::INVALIDE_ERROR_MESSAGE) ?>

            <div class="row">
                <div class="col-md-4">
                    <?= $fcg($form->get($form::INPUT_IMPORT_FILE)); ?>
                </div>
                <div class="col-md-8 text-muted text-small">
                    <ul>
                        <li>Le fichier CSV doit utiliser comme séparateur le '
                            <?= CSVService::SEPARATOR ?>' et avoir les champs suivants : <br/>
                            <?php $h = "";
                            foreach (CategorieStageCsvImportValidator::getImportHeader() as $key) {
                                $h .= sprintf("<strong><span class='mx-2'>%s</span></strong>; ", $key);
                            }
                            echo $h;
                            ?>
                        </li>
                        <li>
                            Laissez le champ
                            <strong><?= CategorieStageCsvImportValidator::HEADER_CODE_CATEGORIE ?></strong>
                            vide pour toute nouvelle catégorie.
                        </li>
                        <li>
                            Les champs <strong><?= CategorieStageCsvImportValidator::HEADER_ACRONYME ?></strong>
                            et <strong><?= CategorieStageCsvImportValidator::HEADER_LIBELLE ?></strong>
                            doivent être unique.
                        </li>
                        <?php //Message éventuelle pour l'import
                        $msg = $this->messenger()->addCurrentMessagesFromFlashMessengerWithNamespace(CategorieStageController::ACTION_IMPORTER . Messenger::NAMESPACED_SEVERITY_SEPARATOR . "*");
                        ?>
                    </ul>
                </div>
            </div>

            <?php if ($msg && $msg->hasMessages()) : ?>
                <div class="row">
                    <div class="col-md-12">
                        <div>
                            <strong><?= $msg ?></strong>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
            <hr/>
            <div class="row">
                <div class="col-md-12">
                    <?= $fcg($form->get($form::INPUT_SUBMIT)); ?>
                </div>
            </div>
            <?= $this->formHidden($form->get($form::CSRF)); ?>
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>

<script>
    $(function () {
        let body = $("body");
        body.off("<?= CategorieStageController::EVENT_IMPORTER?>", closeModal)
            .one("<?= CategorieStageController::EVENT_IMPORTER?>", closeModal);
    })
</script>
