<?php

use Application\Controller\Stage\SessionStageController;
use Application\Form\Stages\SessionStageForm;
use Application\View\Helper\SessionsStages\SessionStageViewHelper;

/**
 * @see SessionStageController::ajouterAction()
 * @var String $title
 * @var SessionStageForm $form
 */

/** @var SessionStageViewHelper $vh */
$vh = $this->sessionStage();
?>

<div class="card card-success">
    <h1 class="page-header card-header">
        <span class="icon icon-ajouter"></span>
        <?= $title ?>
    </h1>
    <div class="card-body">
        <?= $vh->renderForm($form); ?>
    </div>
</div>

<script>
    $(function () {
        let body = $("body");
        body.off("<?= SessionStageController::EVENT_AJOUTER?>", closeModal)
            .one("<?= SessionStageController::EVENT_AJOUTER?>", closeModal);
    })
</script>
