<?php

use Application\Controller\Stage\SessionStageController;
use Application\Entity\Db\SessionStage;
use Application\Form\Misc\ImportForm;
use Application\View\Helper\SessionsStages\SessionStageViewHelper;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @see SessionStageController::importerPlacesTerrainsAction()
 * @var string $title
 * @var SessionStage $sessionStage
 * @var ImportForm $form
 */

/** @var SessionStageViewHelper $vh */
$vh = $this->sessionStage();
?>

<h1 class="page-header">
    <span class="icon icon-importer"></span>
    <?= $title ?>
    <br/>
    <small class="text-muted">
        <?= $sessionStage->getAnneeUniversitaire()->getLibelle() ?> -
        <?= $sessionStage->getGroupe()->getLibelle() ?> -
        <?= $sessionStage->getLibelle() ?>
    </small>
</h1>

<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <?= $vh->renderFormImportation($form); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-small">

            </div>
        </div>
    </div>
</div>

<script>
    $(function () {
        let body = $("body");
        body.off("<?= SessionStageController::EVENT_MODIFIER?>", closeModal)
            .one("<?= SessionStageController::EVENT_MODIFIER?>", closeModal);
    })
</script>
