<?php

use Application\Controller\Stage\SessionStageController;
use Application\Form\Stages\PeriodeStageForm;
use Application\Provider\Misc\Icone;
use Application\View\Helper\SessionsStages\SessionStageViewHelper;
use UnicaenCalendrier\Entity\Db\Date;

/**
 * @see SessionStageController::modifierPeriodeStageAction()
 * @var String $title
 * @var PeriodeStageForm $form
 * @var \Application\Entity\Db\SessionStage $session
 * @var Date $periode
 */
/** @var SessionStageViewHelper $vh */
$vh = $this->sessionStage();
?>

<div class="card card-primary">
    <h1 class="page-header card-header">
        <span class="icon icon-modifier"></span>
        <?= $title ?>
    </h1>
    <div class="card-body">
        <div class="row">
            <div class="col-md-2">
                <strong>Session</strong>
            </div>
            <div class="col-md-10">
                <?= $session->getLibelle() ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                <strong>Dates de la session</strong>
            </div>
            <div class="col-md-10">
                du <?= $session->getDateDebutStage()->format('d/m/Y') ?>
                au <?= $session->getDateFinStage()->format('d/m/Y') ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                <strong>Périodes existantes</strong>
            </div>
            <div class="col-md-4">
                <?php $periodesStages = $session->getDatesPeriodesStages(); ?>
                <?php foreach ($periodesStages as $p):
                    ?>
                    <div class="text-small <?= ($p->getId() == $periode->getId()) ? "text-primary" : null ?>">
                        <span class="ms-3 <?= Icone::FA_ARROW_RIGHT ?>"></span>
                        du <?= $p->getDebut()->format('d/m/Y') ?>
                        au <?= $p->getFin()->format('d/m/Y') ?>
                        <?= ($p->getId() == $periode->getId()) ?"<sup>*</sup>" : null ?>
                    </div>
                <?php endforeach; ?>
            </div>
            <div class="col-md-6">
                <div class="text-small text-primary"><sup>*</sup> : Période selectionnée</div>
            </div>
        </div>
        <hr/>
        <?= $vh->renderPeriodeStageForm($form); ?>
    </div>
</div>

<script>
    $(function () {
        let body = $("body");
        body.off("<?= SessionStageController::EVENT_MODIFIER?>", closeModal)
            .one("<?= SessionStageController::EVENT_MODIFIER?>", closeModal);
    })
</script>
