<?php

use Application\Controller\Notification\FaqQuestionController as Controller;
use Application\Form\Misc\ConfirmationForm;
use Application\View\Helper\Misc\ConfirmationFormViewHelper;

/**
 * @see SessionStageController::supprimerPeriodeStageAction()
 *
 * @var string              $title
 * @var ConfirmationForm    $form
*/

/** @var ConfirmationFormViewHelper $vh */
$vh = $this->confirmation($form)
?>

<div class="card card-danger">
    <h1 class="page-header card-header">
        <span class="icon icon-supprimer"></span>
        <?= $title ?>
    </h1>
    <div class="card-body">
        <?= $vh->render(); ?>
    </div>
</div>

<script>
    $(function () {
        let body = $("body");
        body.off("<?= Controller::EVENT_MODIFIER?>", closeModal)
            .one("<?= Controller::EVENT_MODIFIER?>", closeModal);
    });
</script>