<?php

namespace Console\Rapport;

use DateTime;
use UnicaenMail\Entity\Db\Mail;

class ReportMessage extends Mail
{
    protected ?DateTime $dateDebutAction = null;
    protected ?DateTime $dateFinAction = null;

    protected array $logs=[];
    public function getCorps(): ?string
    {
        return parent::getCorps(); // TODO: Change the autogenerated stub
    }

}