<?php
/** @var \Application\View\Helper\Misc\FooterViewHelper $vh */
$vh = $this->footer();
?>

<footer class="footer-unistrap d-flex flex-wrap justify-content-between align-items-center py-3 pt-0">
    <div class="container-sm d-flex flex-wrap justify-content-between align-items-center">
        <div class="col-md-4">
            <?= $vh->renderLogos() ?>
        </div>

        <div class="nav col-md-8 justify-content-end nav-foot">
            <?= $vh->renderMenuPiedDePage() ?>
        </div>
    </div>
</footer>
