<?php

use Laminas\Navigation\AbstractContainer;
use Laminas\Navigation\Page\AbstractPage;

// Pointeur sur la première page du conteneur
$this->container->rewind();
// On récupère le conteneur en-dessous du 'home'
/** @var AbstractContainer $container */
$container = $this->container->getChildren();

// tri des pages de niveau 1 par 'order'
$sorterByOrder = function(AbstractPage $p1, AbstractPage $p2) { return ($p1->getOrder()?:0) <=> ($p2->getOrder()?:0); };
$pagesNiv1 = iterator_to_array($container);
uasort($pagesNiv1, $sorterByOrder);
?>
<ul class="<?php echo $this->navigation()->menu()->getUlClass(); ?>">
    <?php foreach ($pagesNiv1 as $page): ?>
        <?php if (!$this->navigation()->accept($page)) continue; ?>
        <?php /* @var $page Laminas\Navigation\Page\Mvc */ ?>
        <?php $hasChildren = $page->hasPages() ?>
        <?php if (!$hasChildren): ?>
            <li class="nav-item">
                <a class="nav-link <?= ($page->isActive()) ? 'active' : ''?>"
                    <?= ($page->isActive()) ? 'aria-current="page"' : ''?>
                   href="<?php echo $page->getHref() ?>"
                    <?php if ($page->getTarget() != ""): ?>
                        target="<?php echo $page->getTarget(); ?>"
                    <?php endif; ?>>
                    <?php if ($page->get("icon") !== ""): ?>
                        <span class="<?php echo $page->get("icon"); ?>"></span>
                    <?php endif; ?>
                    <?php echo $this->escapeHtml($this->translate($page->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?>
                </a>
            </li>
        <?php else: ?>
            <?php
            //check if access is allowed at least one item
            $access = false;
            foreach ($page->getPages() as $child) {
                if ($this->navigation()->accept($child) && $child->get("separator") !== true) {
                    $access = true;
                }
            }
            if ($access) :
                ?>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle <?= ($page->isActive(true)) ? ' active' : '' ?>"
                        <?= ($page->isActive()) ? 'aria-current="page"' : ''?>
                       href="#"
                       role="button" data-bs-toggle="dropdown" aria-expanded="false"
                    >
                        <?php if ($page->get("icon") != ""): ?>
                            <span class="icon">
                                <i class="<?php echo $page->get("icon"); ?>"></i>
                            </span>
                        <?php endif; ?>
                        <?php echo $this->escapeHtml($this->translate($page->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?>
                        <!--                        <b class="caret"></b>-->
                    </a>
                    <ul class="dropdown-menu">
                        <?php
                        // tri des pages de niveau 2 par 'order'
                        $pagesNiv2 = $page->getPages();
                        uasort($pagesNiv2, $sorterByOrder);
                        ?>
                        <?php foreach ($pagesNiv2 as $child): ?>
                            <?php if (!$this->navigation()->accept($child)) continue; ?>
                            <?php if ($child->get("dropdown-header") === true): ?>
                                <li class="dropdown-header">
                                    <?php if ($child->get("icon") != ""): ?>
                                        <span class="icon">
                                            <i class="<?php echo $child->get("icon"); ?>"></i>
                                        </span>
                                    <?php elseif (in_array('divider', explode(' ', $child->getClass()))): ?>
                                        <div class="dropdown-divider <?php echo $child->getClass() ?>"></div>
                                    <?php endif; ?>
                                    <?php echo $this->escapeHtml($this->translate($child->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?>
                                </li>
                                <?php
                                continue;
                            endif;
                            ?>
                            <?php if ($child->get("separator") === true): ?>
                                <li class="divider"></li>
                                <?php
                                continue;
                            endif;
                            ?>
                            <li>
                                <a class="dropdown-item <?= ($child->isActive(true)) ? ' active' : '' ?>"
                                    <?= ($child->isActive()) ? 'aria-current="page"' : ''?>
                                   href="<?php echo $child->getHref() ?>"
                                    <?php if ($child->getTarget() != ""): ?>
                                        target="<?php echo $child->getTarget(); ?>"
                                    <?php endif; ?>>
                                    <?php if ($child->get("icon") != ""): ?>
                                        <span class="icon">
                                            <i class="<?php echo $child->get("icon"); ?>"></i>
                                        </span>
                                    <?php endif; ?>
                                    <?php echo $this->escapeHtml($this->translate($child->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?>
                                </a>
                            </li>
                        <?php endforeach ?>
                    </ul>
                </li>
            <?php endif; ?>
        <?php endif ?>
    <?php endforeach ?>
</ul>