<?php

use Application\Controller\Notification\FaqQuestionController as Controller;
use Application\Entity\Db\Faq;
use Application\Provider\Privilege\FaqPrivileges;
use Application\View\Helper\Notification\FAQViewHelper;

/**
 * @see FaqQuestionController::indexAction()
 * @var Faq[] $questions
 */
/** @var FAQViewHelper $vh */
$vh = $this->faq();
$canAdd = $vh->hasPrivilege(FaqPrivileges::FAQ_QUESTION_AFFICHER);
?>

<h1 class="page-header">
    <span class="icon">
        <i class="fas fa-question-circle text-primary"></i>
    </span>
    Foire aux questions
</h1>


<div class="card mt-3">
    <?php if ($canAdd) : ?>
        <div class="card-header card-sub-header text-end">
            <?= $vh->lienAjouter() ?>
        </div>
    <?php endif; ?>
    <div class="card-body" id="liste-faq" data-url="<?= $this->url(Controller::ROUTE_LISTER, [], [], true) ?>">
        <?= $vh->renderListe($questions) ?>
    </div>
</div>

<script type="text/javascript">
    //Rechargement de la page sur event
    $(function () {
        let body = $("body");
        body.on("<?=Controller::EVENT_AJOUTER?> "
            + "<?=Controller::EVENT_MODIFIER?> "
            + "<?=Controller::EVENT_SUPPRIMER?> "
            , function () {
                $("#liste-faq").refresh();
            });
    });
</script>
