<?php

/** @see ParametreController::indexAction() */
use Application\Controller\Parametre\ParametreController;
use Application\Entity\Db\Parametre;
use Application\View\Helper\Parametres\ParametreViewHelper;


/**
 * @see ParametreController::indexAction()
 *

 * @var Parametre[] $parametres
 */
$this->headTitle("Paramères");
/** @var ParametreViewHelper $vh */
$vh = $this->parametre();
?>


<h1 class="page-header">
    <span class="icon">
        <i class="fas fa-cog"></i>
    </span>
    Gestion des paramètres de l'application
</h1>

<div class="card mt-3">
 <div class="card-body" id="parametres-content" data-url="<?= $this->url(ParametreController::ROUTE_LISTER, [], [], true) ?>">
    <?= $vh->renderListe($parametres) ?>
</div>
</div>

<script type="text/javascript">
    $(function () {
        let body = $("body");

        body.on("<?=ParametreController::EVENT_MODIFIER?> "
            , function () {
                $("#parametres-content").refresh();
            });
    })
</script>