<?php

/** @see ParametreController::modifierAction() */
use Application\Controller\Parametre\ParametreController;
use Application\Form\Preferences\PreferenceForm;
use Application\View\Helper\Parametres\ParametreViewHelper;

/**
 * @see ParametreController::modifierAction()
 * @var string $title
 * @var PreferenceForm $form
 */

/** @var ParametreViewHelper $vh */
$vh = $this->parametre();
?>
<div class="card card-primary">
    <h1 class="page-header card-header">
        <span class="icon icon-modifier"></span>
        <?= $title ?>
    </h1>
    <div class="card-body">
        <?= $vh()->renderForm($form); ?>
    </div>
</div>

<script>
    $(function () {
        let body = $("body");
        body.off("<?= ParametreController::EVENT_MODIFIER?>", closeModal)
            .one("<?= ParametreController::EVENT_MODIFIER?>", closeModal);
    })
</script>