<?php

use Application\Controller\AnneeUniversitaire\AnneeUniversitaireController;
use Application\Form\Annees\AnneeUniversitaireForm;
use Application\Form\Annees\Fieldset\AnneeUniversitaireFieldset;


/**
 * @see AnneeUniversitaireController::ajouterAction();
 * @see AnneeUniversitaireController::modifierAction();
 * @var String $title
 *
 * @var AnneeUniversitaireForm $form
 */

$fe = $this->formErrors();
$fcg = $this->formControlGroup();
$fr = $this->formrow();
$fct = $this->formControlText();

$fieldset = $form->getEntityFieldset();
?>

<?= $this->form()->openTag($form->prepare()) ?>
<?= $fe($form->prepare(), AnneeUniversitaireForm::INVALIDE_ERROR_MESSAGE) ?>
<?= $fr($fieldset->get(AnneeUniversitaireFieldset::ID)); ?>
<?= $fr($fieldset->get(AnneeUniversitaireFieldset::CODE)); ?>

    <div class="row">
        <div class="col-md-12">
            <?= $fct($fieldset->get(AnneeUniversitaireFieldset::LIBELLE)); ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <?= $fcg($fieldset->get(AnneeUniversitaireFieldset::DATE_DEBUT)); ?>
        </div>
        <div class="col-md-6">
            <?= $fcg($fieldset->get(AnneeUniversitaireFieldset::DATE_FIN)); ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-10">
            <?= $fcg($form->get(AnneeUniversitaireForm::INPUT_SUBMIT)); ?>
        </div>
    </div>

<?= $this->formHidden($form->get(AnneeUniversitaireForm::CSRF)); ?>
<?= $this->form()->closeTag(); ?>