<?php

use Application\Controller\Terrain\TerrainStageController;
use Application\Form\Misc\ImportForm;
use Application\Service\Misc\CSVService;
use Application\Validator\Import\TerrainStageCsvImportValidator;
use UnicaenApp\View\Helper\Messenger;

/**
 * @see TerrainStageController::importerAction()
 * @var string $title
 * @var ImportForm $form
 */
$fe = $this->formErrors();
$fr = $this->formrow();
$fcg = $this->formControlGroup();
?>


<div class="card card-primary">
    <h1 class="page-header card-header">
        <span class="icon icon-importer"></span>
        <?= $title ?>
    </h1>
    <div class="card-body">
        <div class="fieldset">
            <?= $this->form()->openTag($form->prepare()) ?>
            <?= $fe($form->prepare(), $form::INVALIDE_ERROR_MESSAGE) ?>

            <div class="row">
                <div class="col-md-4">
                    <?= $fcg($form->get($form::INPUT_IMPORT_FILE)); ?>
                </div>
                <div class="col-md-8 text-muted text-small">
                    <ul>
                        <li>Le fichier CSV doit :
                            <ul>
                                <li> utiliser comme séparateur le '<?= CSVService::SEPARATOR ?>'</li>
                                <li> être encodé en utf8</li>
                                <?php  $ob = "<sup title='Champs obligatoire'>*</sup>"; ?>
                                <li> avoir les champs suivants : (<?=$ob?> = Champs obligatoires)<br/>
                                    <?php $h = "";
                                    foreach (TerrainStageCsvImportValidator::getImportHeader() as $key) {
                                        $obligatoire =  TerrainStageCsvImportValidator::isChampsObligatoire($key);
                                        $h .= sprintf("<strong><span class='mx-2'>%s %s </span></strong>; ", $key, (($obligatoire) ? $ob : ''));
                                    }
                                    echo $h;
                                    ?>
                            </ul>
                        </li>
                        <li>
                            Le champ
                            <strong><?= TerrainStageCsvImportValidator::HEADER_CODE_CATEGORIE ?></strong>
                            doit correspondre au code de la catégorie.
                        </li>
                        <li>
                            Laissez le champ
                            <strong><?= TerrainStageCsvImportValidator::HEADER_CODE_TERRAIN ?></strong>
                            vide pour tout nouveau terrain de stage utilisant la nomenclature par défaut : "[Code de la catégorie]_XXX".
                        </li>
                        <li>
                            Le champ <strong><?= TerrainStageCsvImportValidator::HEADER_LIBELLE ?></strong>
                            doit être unique.
                        </li>
                        <?php //Message éventuelle pour l'import
                        $msg = $this->messenger()->addCurrentMessagesFromFlashMessengerWithNamespace(TerrainStageController::ACTION_IMPORTER . Messenger::NAMESPACED_SEVERITY_SEPARATOR . "*");
                        ?>
                    </ul>
                </div>
            </div>

            <hr/>
            <div class="row">
                <div class="col-md-12">
                    <?= $fcg($form->get($form::INPUT_SUBMIT)); ?>
                </div>
            </div>

            <?php if ($msg && $msg->hasMessages()) : ?>
                <div class="row">
                    <div class="col-md-12">
                        <div>
                            <strong><?= $msg ?></strong>
                        </div>
                    </div>
                </div>
            <?php endif; ?>

            <?= $this->formHidden($form->get($form::CSRF)); ?>
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>

<script>
    $(function () {
        let body = $("body");
        body.off("<?= TerrainStageController::EVENT_IMPORTER?>", closeModal)
            .one("<?= TerrainStageController::EVENT_IMPORTER?>", closeModal);
    })
</script>
