<?php

use Application\Controller\Convention\ConventionStageController;
use Application\Form\Misc\ConfirmationForm;


/**
 * @see ConventionStageController::supprimerAction()
 *
 * @var PhpRenderer         $this
 * @var string              $title
 * @var ConfirmationForm    $form
 */
?>

<div class="card card-danger">
    <h1 class="page-header card-header">
        <span class="icon icon-supprimer"></span>
        <?= $title ?>
    </h1>
    <div class="card-body">

        <div class='alert alert-warning'>
            <strong>Cette action supprimera également la liste des signataires, les fichiers téléchargés ...</strong>
        </div>

        <?= $this->confirmation($form); ?>
    </div>
</div>
<script>
    $(function () {
        let body = $("body");
        body.off("<?= ConventionStageController::EVENT_SUPPRIMER?>", closeModal)
            .one("<?= ConventionStageController::EVENT_SUPPRIMER?>", closeModal);
    });
</script>
