<?php

use Application\Controller\Groupe\GroupeController;
use Application\Form\Groupe\Fieldset\GroupeFieldset;
use Application\Form\Groupe\GroupeForm;


/**
 * @see GroupeController::ajouterAction()
 * @see GroupeController::modifierAction()
 *

 * @var GroupeForm $form
 * @var GroupeFieldset $fieldset
 */

$fe = $this->formErrors();
$fcg = $this->formControlGroup();
$fr = $this->formrow();
$fct = $this->formControlText();

$fieldset = $form->getEntityFieldset();
?>


<?= $this->form()->openTag($form->prepare()) ?>

<?= $fe($form->prepare(), GroupeForm::INVALIDE_ERROR_MESSAGE) ?>
<?= $fr($fieldset->get(GroupeFieldset::ID)); ?>

<div class="row">
    <div class="col-md-6">
        <?= $fct($fieldset->get(GroupeFieldset::LIBELLE)); ?>
    </div>
    <div class="col-md-6">
        <?= $fcg($fieldset->get(GroupeFieldset::ANNEE_UNIVERSITAIRE)); ?>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <?= $fcg($fieldset->get(GroupeFieldset::NIVEAU_ETUDE)); ?>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <?= $fcg($form->get(GroupeForm::INPUT_SUBMIT)); ?>
    </div>
</div>

<?= $this->formHidden($form->get(GroupeForm::CSRF)); ?>
<?= $this->form()->closeTag(); ?>

<script type="text/javascript">
    $(function () {
        //Affichage des selectpicker des le départ
        $('.selectpicker').selectpicker('render');
    })
</script>