<?php

use Application\Form\Referentiel\Fieldset\ReferentielPromoFieldset;
use Application\Form\Referentiel\ReferentielPromoForm;

/**
 * @see ReferentielPromoController::ajouterAction()
 * @see ReferentielPromoController::modifierAction()
 *
 * @var string $title
 * @var ReferentielPromoForm $form
 */

$fcg = $this->formControlGroup();
$fe = $this->formErrors();
$fr = $this->formrow();
$fct = $this->formControlText();

$title = $form->getTitle();
/** @var ReferentielPromoFieldset $fieldset */
$fieldset = $form->getEntityFieldset();
?>

<div class="fieldset">
    <?= $this->form()->openTag($form->prepare()) ?>
            <?= $fe($form->prepare(), $form::INVALIDE_ERROR_MESSAGE) ?>
            <?= $fr($fieldset->get($form::INPUT_ID)); ?>

    <div class="row">
        <div class="col-md-6">
            <?= $fcg($fieldset->get($fieldset::SOURCE)); ?>
        </div>
        <div class="col-md-6">
            <?= $fcg($fieldset->get($fieldset::CODE)); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <?= $fct($fieldset->get($fieldset::LIBELLE)); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <?= $fct($fieldset->get($fieldset::CODE_PROMO)); ?>
            <div class="text-small text-muted">Code de la promo dans l'annuaire LDAP, code de la VET dans apogée / Pégase ...</div>
        </div>
        <div class="col-md-2">
            <?= $fcg($fieldset->get($fieldset::ORDRE)); ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <?= $fcg($form->get($form::INPUT_SUBMIT)); ?>
        </div>
    </div>

    <?= $this->formHidden($form->get($form::CSRF)); ?>
    <?= $this->form()->closeTag(); ?>
</div>


<script type="text/javascript">
    $(function () {
        //Affichage des selectpicker des le départ
        $('.selectpicker').selectpicker('render');
    });
</script>