<?php

use Application\Controller\AnneeUniversitaire\AnneeUniversitaireController;
use Application\Entity\Db\AnneeUniversitaire;
use Application\Provider\Privilege\AnneePrivileges;
use Application\View\Helper\Annees\AnneeUniversitaireViewHelper;
use UnicaenEtat\Entity\Db\EtatInstance;

/**
 * @see AnneeUniversitaireController::listerAction()
 * @var AnneeUniversitaire[] $annees
 * @var string $tableId
 */

$tableId = "liste-annees-universitaires";

/** @var AnneeUniversitaireViewHelper $vh */
$vh = $this->anneeUniversitaire();

$canSee = $vh->hasPrivilege(AnneePrivileges::ANNEE_UNIVERSITAIRE_AFFICHER);
$canAdd = $vh->actionAllowed(AnneeUniversitaireController::ACTION_AJOUTER);
?>

<div class="card">
    <div class="card-header"><strong>Liste des années universitaires</strong></div>
    <?php if ($canAdd) : ?>
        <div class="card-header card-sub-header text-end">
            <?= $vh->lienAjouter() ?>
        </div>
    <?php endif; ?>

    <div class="card-body">


        <table id="<?= $tableId ?>" class="table table-hover table-condensed tableData">
            <thead>
            <tr>
                <th class="col-md-6" data-priority="0">Libellé</th>
                <th class="col-md-2" data-type="num">Début</th>
                <th class="col-md-2 " data-type="num">Fin</th>
                <th class="col-md-2 no-search text-end" data-type="num">Etat</th>
            </tr>
            </thead>
            <tbody>
            <?php /** @var AnneeUniversitaire $annee */
            foreach ($annees as $annee):
                $vh->setAnneeUniversitaire($annee);
                /** @var EtatInstance $etat */
                $etat = $annee->getEtatActif();
                $bg = match (true) {
                    $annee->hasEtatNonValide() => "table-danger",
                    $annee->hasEtatEnConstruction() => "table-info",
                    $annee->hasEtatFuture() => "table-muted",
                    $annee->hasEtatEnCours() => "table-primary",
                    $annee->hasEtatTerminee() => "table-success",
                    default => "table-danger",
                }
                ?>

                <tr class="<?= $bg ?>">
                    <td data-filter="<?= $annee->getLibelle() ?>" data-order="<?= $annee->getLibelle() ?>">
                        <?= $vh->lienAfficher() ?>
                    </td>
                    <td class="" data-order="<?= $annee->getDateDebut()->getTimestamp() ?>">
                        <?= $annee->getDateDebut()->format('d/m/Y') ?>
                    </td>
                    <td class="" data-order="<?= $annee->getDateFin()->getTimestamp() ?>">
                        <?= $annee->getDateFin()->format('d/m/Y') ?>
                    </td>
                    <td class="text-end" data-order="<?= (isset($etat) ? $etat->getType()->getOrdre() : PHP_INT_MIN) ?>"
                        style="color:<?= $etat->getType()->getCouleur() ?>"
                    >
                        <span class="<?= $etat->getType()->getIcone() ?>"></span> <?= $etat->getTypeLibelle() ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>


<script type="text/javascript">
    $(function () {
        let options = generateDataTableSetings({
            stateSave: false,
            retrieve: true,
            "order": [[1, "desc"], [2, "desc"], [3, "asc"], [0, "asc"]],
        })
        $("#<?= $tableId ?>").DataTable(options);
    })
</script>
