<?php

use Application\Controller\AnneeUniversitaire\AnneeUniversitaireController;
use Application\Form\Annees\AnneeUniversitaireForm;
use Application\View\Helper\Annees\AnneeUniversitaireViewHelper;


/**
 *
 * @see AnneeUniversitaireController::ajouterAction()
 * @var string $title
 * @var AnneeUniversitaireForm $form
 */

/** @var AnneeUniversitaireViewHelper $vh */
$vh = $this->anneeUniversitaire();
?>


<div class="card card-success">
    <h1 class="page-header card-header">
        <span class="icon icon-ajouter"></span>
        <?= $title ?>
    </h1>
    <div class="card-body">
        <?= $vh->renderForm($form); ?>
    </div>


    <div class="card-footer">
        <div class="row">
            <div class="col-md-12">
                <?= $this->backButton("Liste des années")->backTo($this->url(AnneeUniversitaireController::ROUTE_INDEX, [], [], true)) ?>
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {
        let body = $("body");
        body.off("<?= AnneeUniversitaireController::EVENT_AJOUTER?>", closeModal)
            .one("<?= AnneeUniversitaireController::EVENT_AJOUTER?>", closeModal);
    })
</script>