<?php

use Application\Controller\Parametre\ParametreCoutAffectationController;
use Application\Controller\Parametre\ParametreCoutTerrainController;
use Application\Entity\Db\ParametreTerrainCoutAffectationFixe;
use Application\Provider\Privilege\ParametrePrivileges;
use Application\View\Helper\Parametres\ParametreCoutTerrainViewHelper;

/**
 * @see ParametreCoutAffectationController::indexAction()
 *
 * @var ParametreTerrainCoutAffectationFixe[] $parametres
 */
$this->headTitle("Paramères");

/** @var ParametreCoutTerrainViewHelper $vh */
$vh = $this->parametreCoutTerrain();
$canAdd = $vh->hasPrivilege(ParametrePrivileges::PARAMETRE_AJOUTER);
?>


<h1 class="page-header">
    <span class="icon">
        <i class="fas fa-cog"></i>
    </span>
    Gestion des terrains de stages ayant un coûts fixes
</h1>

<div class="card mt-3">
    <?php if($canAdd) :?>
        <div class="card-header card-sub-header text-end">
            <?= $vh->lienAjouter() ?>
        </div>
    <?php endif; ?>
    <div class="card-body" id="parametres-content" data-url="<?= $this->url(ParametreCoutTerrainController::ROUTE_LISTER, [], [], true) ?>">
    <?= $vh->renderListe($parametres) ?>
</div>
</div>


<script type="text/javascript">
    //Rechargement de la page sur event
    $(function () {
        let body = $("body");

        body.on("<?=ParametreCoutTerrainController::EVENT_AJOUTER?> "
            + "<?=ParametreCoutTerrainController::EVENT_MODIFIER?> "
            + "<?=ParametreCoutTerrainController::EVENT_SUPPRIMER?> "
            , function () {
                $("#parametres-content").refresh();
            });
    })
</script>