<?php

use Application\Controller\Parametre\ParametreCoutTerrainController;
use Application\Form\Parametre\ParametreCoutTerrainForm;
use Application\View\Helper\Parametres\ParametreCoutTerrainViewHelper;

/**
 * @see ParametreCoutTerrainController::modifierAction()
 * @var string $title
 * @var ParametreCoutTerrainForm $form
 */

/** @var ParametreCoutTerrainViewHelper $vh */
$vh = $this->parametreCoutTerrain();
?>
<div class="card card-primary">
    <h1 class="page-header card-header">
        <span class="icon icon-modifier"></span>
        <?= $title ?>
    </h1>
    <div class="card-body">
        <?= $vh()->renderForm($form); ?>
    </div>
</div>

<script>
    $(function () {
        let body = $("body");
        body.off("<?= ParametreCoutTerrainController::EVENT_MODIFIER?>", closeModal)
            .one("<?= ParametreCoutTerrainController::EVENT_MODIFIER?>", closeModal);
    })
</script>