<?php

use Application\Controller\Contrainte\ContrainteCursusEtudiantController;
use Application\Form\Misc\ConfirmationForm;


/**
 * @see ContrainteCursusEtudiantController::invaliderAction()
 *

 * @var string $title
 * @var ConfirmationForm $form
 */
?>

<div class="card card-danger">
    <h1 class="page-header card-header">
        <span class="icon icon-unchecked"></span>
        <?= $title ?>
    </h1>
    <div class="card-body">
        <?= $this->confirmation($form); ?>
    </div>
</div>

<script>
    $(function () {
        let body = $("body");
        body.off("<?= ContrainteCursusEtudiantController::EVENT_MODIFIER?>", closeModal)
            .one("<?= ContrainteCursusEtudiantController::EVENT_MODIFIER?>", closeModal);
    });
</script>
