<?php

use Application\Form\Parametre\Fieldset\ParametreCoutAffectationFieldset;
use Application\Form\Parametre\ParametreCoutAffectationForm;
use UnicaenApp\View\Helper\Messenger;

/**
 * @see ParametresStagesController::ajouterCoutAffectationAction()
 * @see ParametresStagesController::modifierCoutAffectationAction()
 *
 * @var String $title
 * @var ParametreCoutAffectationForm $form
 */

$fcg = $this->formControlGroup();
$fe = $this->formErrors();
$fr = $this->formrow();

/** @var ParametreCoutAffectationFieldset $fieldset */
$fieldset = $form->getEntityFieldset();
?>

<div class="fieldset">
    <?= $this->form()->openTag($form->prepare()) ?>
    <?= $fe($form->prepare(), $form::INVALIDE_ERROR_MESSAGE) ?>
    <?= $fr($fieldset->get($fieldset::ID)); ?>

    <?php //Gestions des messages du formulaire
    $namespace = $form->getMessageNamespace() . Messenger::NAMESPACED_SEVERITY_SEPARATOR . "*";
    $msg = $this->messenger()->addCurrentMessagesFromFlashMessengerWithNamespace($namespace);
    ?>
    <?php if ($msg && $msg->hasMessages()) : ?>
        <div class="messenger row my-3">
            <div class="col-md-12">
                <?= $msg ?>
            </div>
        </div>
    <?php endif; ?>

    <div class="row">
        <div class="col-md-6">
            <?= $fcg($fieldset->get($fieldset::RANG)); ?>
        </div>
        <div class="col-md-6">
            <?= $fcg($fieldset->get($fieldset::COUT)); ?>
        </div>
    </div>


    <div class="row">
        <div class="col-md-12">
            <?= $fcg($form->get($form::INPUT_SUBMIT)); ?>
        </div>
    </div>
    <?= $this->formHidden($form->get($form::CSRF)); ?>
    <?= $this->form()->closeTag(); ?>

</div>

