<?php

use Application\Controller\Etudiant\EtudiantController;
use Application\Entity\Db\Etudiant;
use Application\Entity\Db\Groupe;
use Application\Provider\EtatType\EtudiantEtatTypeProvider;
use Application\Provider\Privilege\EtudiantPrivileges;
use Application\View\Helper\Etudiant\EtudiantViewHelper;

/**
 * @see EtudiantController::indexAction()
 * @see EtudiantController::rechercherAction()
 * @var Etudiant[] $etudiants
 */

/** @var EtudiantViewHelper $vh */
$vh = $this->etudiant();
$tableId = "liste-etudiants";

$groupeOrder = [];
/** @var Groupe[] $groupes */
$groupes = [];
foreach ($etudiants as $etudiant) {
    /** @var Groupe $groupe */
    foreach ($etudiant->getGroupes() as $groupe) {
        if (!isset($groupes[$groupe->getId()])) {
            $groupes[$groupe->getId()] = $groupe;
        }
    }
}
$groupes = Groupe::sortGroupes($groupes);
$i = 0;
foreach ($groupes as $g) {
    $groupeOrder[$g->getId()] = ++$i;
}

$canAdd = $vh->hasPrivilege(EtudiantPrivileges::ETUDIANT_AJOUTER);
?>

<div class="card">
    <div class="card-header">
        Liste des étudiants
    </div>
    <?php if($canAdd) : ?>
    <div class="card-header card-sub-header text-end">
        <?= $vh->lienAjouter() ?>
        <?= $vh->lienImporter() ?>
        <span class="dropdown">
        <a class="btn btn-primary dropdown-toggle" href="#" role="button" id="" data-bs-toggle="dropdown"
        aria-expanded="false">
        <span class="icon icon-exporter"></span> Exporter
        </a>
        <ul class="dropdown-menu" id="exports-menu"></ul>
        </span>
    </div>
    <?php endif; ?>

    <div class="card-body">
        <table id="<?= $tableId ?>" class="table table-hover table-condensed">
            <thead>
            <tr>
                <th class="col-md-1" data-priority="0">n° étudiant</th>
                <th class="col-md-3">Nom</th>
                <th class="col-md-2">Prénom</th>
                <th class="col-md-2">Groupe(s)</th>
                <th class="col-md-2 no-search text-end" data-type="num">État du cursus</th>
            </tr>
            </thead>
            <?php foreach ($etudiants as $etudiant):
                $vh->setEtudiant($etudiant);
                $etat = $etudiant->getEtatActif();
                $bg = match (true) {
                    $etudiant->hasEtatEnDispo() =>  "table-muted",
                    $etudiant->hasEtatCursusValide() =>  "table-success",
                    $etudiant->hasEtatCursusNonValide() =>  "table-success", // a revoir
                    $etudiant->hasEtatCursusEnCours() =>  "table-primary",
                    $etudiant->hasEtatCursusEnConstruction() =>  "table-info",
                    $etudiant->hasEtatEnAlerte() =>  "table-warning",
                    $etudiant->hasEtatEnErreur() =>  "table-danger",
                    default => "table-danger",
                }
                ?>
                <tr class="<?= $bg ?>">
                    <td data-filter="<?= $etudiant->getNumEtu() ?>"
                        data-order="<?= $etudiant->getNumEtu() ?>"
                        data-export="<?= $etudiant->getNumEtu() ?>"
                    >
                        <?= $vh->lienAfficher() ?>
                    </td>
                    <td>
                        <?= $etudiant->getNom() ?>
                    </td>
                    <td>
                        <?= $etudiant->getPrenom() ?>
                    </td>

                    <?php //Groupes de l'étudiant
                    $groupesLibelle = "";
                    $groupesFilterValue = "";
                    $groupesExportValue = "";
                    $groupesOrderValue = "";
                    $groupes = $etudiant->getGroupes()->toArray();
                    if (empty($groupes)) {
                        $groupesLibelle = "<span class='text-muted'>Aucun</span>";
                        $groupesExportValue = "Aucun";
                        $groupesFilterValue = "Aucun";
                        $groupesOrderValue = -1;
                    } else {
                        $groupes = Groupe::sortGroupes($groupes);
                        $groupes = array_reverse($groupes); //pour l'affichage ici, on les prend par ordre décroissant
                        $groupesOrderValue = $groupeOrder[current($groupes)->getId()];
                        /** @var Groupe $groupe */
                        foreach ($groupes as $groupe) {
                            $groupesFilterValue .= " " . $groupe->getLibelle() . " (" . $groupe->getAnneeUniversitaire()->getLibelle() . ')';
                            $groupeClass = "";
                            if ($groupe->getAnneeUniversitaire()->hasEtatTerminee()
                                || $groupe->getAnneeUniversitaire()->hasEtatNonValide()
                            ) {
                                $groupeClass = "text-muted";
                            }
                            $groupesLibelle .= sprintf("<div class='%s'>%s <span class='text-small text-muted'>(%s)</span></div>",
                                $groupeClass,
                                $groupe->getLibelle(),
                                $groupe->getAnneeUniversitaire()->getLibelle()
                            );
                            $groupesExportValue .= sprintf("%s (%s), ",
                                $groupe->getLibelle(), $groupe->getAnneeUniversitaire()->getLibelle()
                            );
                        }
                        $groupesExportValue = substr_replace($groupesExportValue, "", -1);
                        $groupesExportValue = substr_replace($groupesExportValue, "", -1);
                    }
                    ?>
                    <td data-filter="<?= $groupesFilterValue ?>"
                        data-order="<?= $groupesOrderValue ?>"
                        data-export="<?= $groupesExportValue ?>"
                        data-type="num">
                        <?= $groupesLibelle ?>
                    </td>
                    <?php
                    $etatExportValue = ($etat) ? $etat->getTypeLibelle() : "Indéterminé";
                    $info = ($etat) ?$etat->getInfos() : null;
                    $etatExportValue .= (isset($info) && $info != "") ? " : " . $info : "";
                    ?>
                    <td class="text-end" data-order="<?= ($etat) ? ($etat->getType()->getOrdre()) : PHP_INT_MIN ?>"
                        data-export="<?= $etatExportValue ?>"
                        style="color:<?=  (isset($etat)) ? $etat->getType()->getCouleur() : "" ?>"
                    >
                        <span class="<?= (isset($etat)) ? $etat->getType()->getIcone() : "fa fa-question" ?>"></span>
                        <?= (isset($etat)) ? $etat->getTypeLibelle() : "Indéterminé" ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        let options = generateDataTableSetings(
            {
                stateSave: false,
                retrieve: false,
                "order": [[4, "asc"], [3, "asc"], [1, "asc"], [2, "asc"], [0, "asc"]],
                "lengthMenu": [[50, 100, 250, -1], [50, 100, 250, "Tous"]],
                'dom': "<'row' <'col-sm-12 col-md-6 'l><'col-sm-12 col-md-6' f><'hidden' B>>" +
                    "<'row' <'col-sm-12'tr> >" +
                    "<'row' <'col-sm-12 col-md-5'i> <'col-sm-12 col-md-7'p>>",
                buttons: getExportButtonSetings("Les étudiants"),
            }
        );
        $("#<?= $tableId ?>").DataTable(options);
        //Rajout d'écouteur pour les exports
        $("#<?= $tableId ?>_wrapper .export-btn").appendTo("#exports-menu").addClass("dropdown-item");

    });
</script>