<?php

use Application\Controller\Contact\ContactStageController;
use Application\Controller\Referentiel\ReferentielController;
use Application\Entity\Db\Source;
use Application\Form\Contacts\ContactStageForm;
use Application\Form\Contacts\Fieldset\ContactStageFieldset;

/**
 * @see ContactStageController::ajouterAction()
 * @see ContactStageController::modifieAction()
 * @var ContactStageForm $form
 * @var ContactStageFieldset $fieldset
 */

$fe = $this->formErrors();
$fcg = $this->formControlGroup();
$fr = $this->formrow();
$fct = $this->formControlText();

/** @var ContactStageFieldset $fieldset */
$fieldset = $form->getEntityFieldset();
$formId='form-contact-stage';
$form->setAttribute('id', $formId);
$etudiant = $fieldset->getEtudiant();
?>

<div class="fieldset">


    <?= $this->form()->openTag($form->prepare()) ?>
    <?= $fe($form->prepare(), $form::INVALIDE_ERROR_MESSAGE) ?>
    <?= $fr($fieldset->get($fieldset::ID)) ?>
    <?= $fr($fieldset->get($fieldset::ETUDIANT_ID)) ?>
    <?= $fr($fieldset->get($fieldset::STAGE_ID)) ?>

    <div class="row">
        <div class="col-md-4">
            <?= $fcg($fieldset->get($fieldset::CONTACT)) ?>
        </div>
        <div class="col-md-4">
            <?= $fcg($fieldset->get($fieldset::SESSION)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <?= $fct($fieldset->get($fieldset::ETUDIANT)) ?>
            <?php if(!$etudiant) :?>
            <div class="text-small">
                Rechercher l'étudiant par Nom / Prénom. 3 caractères minimum.
            </div>
            <?php endif; ?>
        </div>
    </div>

    <hr/>
    <?php $inputs = [];
    $inputs[] = $fieldset->get($fieldset::IS_VISIBLE_ETUDIANT);
    $inputs[] = $fieldset->get($fieldset::IS_RESPONSABLE_STAGE);
    $inputs[] = $fieldset->get($fieldset::CAN_VALIDER_STAGE);
    $inputs[] = $fieldset->get($fieldset::SEND_MAIL_AUTO_VALIDATION_STAGE);
    $inputs[] = $fieldset->get($fieldset::SEND_MAIL_AUTO_RAPPEL_VALIDATION_STAGE); ?>
    <?php foreach ($inputs as $input): ?>
        <div class="row">
            <div class="col-md-12">
                <div class="d-flex">
                    <div class="form-check form-switch ms-1">
                        <?= $this->formelement($input) ?>
                        <?= $this->formlabel($input) ?>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
    <hr/>
    <div class="row">
        <div class="col-md-4">
            <div class="h-100 d-flex">
                <div class="form-check form-switch" style="margin-top: auto; margin-bottom: auto">
                    <?php $input = $fieldset->get($fieldset::IS_SIGNATAIRE_CONVENTION); ?>
                    <?= $this->formelement($input) ?>
                    <?= $this->formlabel($input) ?>
                </div>
            </div>
        </div>
        <?php $input = $fieldset->get($fieldset::PRIORITE_ORDRE_SIGNATURE) ?>
        <div class="col-md-4">
            <div class="h-100 d-flex">
                <div  style="margin-top: auto; margin-bottom: auto">
                    <?= $this->formlabel($input) ?>
                </div>
            </div>
        </div>
        <?php $input->setLabel("") ?>
        <div class="col-md-2">
            <div class="h-100 d-flex">
                <div style="margin-top: auto; margin-bottom: auto">
                    <?= $fcg($input) ?>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <?= $fcg($form->get($form::INPUT_SUBMIT)); ?>
        </div>
    </div>
    <?= $this->formHidden($form->get($form::CSRF)); ?>
    <?= $this->form()->closeTag(); ?>
</div>

<script type="text/javascript">
    $(function () {
        $('.selectpicker').selectpicker('render');
    });
</script>
