<?php

use Application\Controller\Contrainte\ContrainteCursusController;
use Application\Form\Contrainte\ContrainteCursusForm;
use Application\View\Helper\ContrainteCursus\ContrainteCursusViewHelper;


/**
 * @see ContrainteCursusController::ajouterAction()

 * @var string $title
 * @var ContrainteCursusForm $form
 */


/** @var ContrainteCursusViewHelper $vh */
$vh = $this->administrationContrainteCursus();
?>

<div class="card card-success">
    <h1 class="page-header card-header">
        <span class="icon icon-ajouter"></span>
        <?= $title ?>
    </h1>
    <div class="card-body">
        <?= $vh()->renderForm($form); ?>
    </div>
</div>

<script>
    $(function () {
        let body = $("body");
        body.off("<?= ContrainteCursusController::EVENT_AJOUTER?>", closeModal)
            .one("<?= ContrainteCursusController::EVENT_AJOUTER?>", closeModal);
    })
</script>