<?php

use Application\Controller\Contrainte\ContrainteCursusController;
use Application\Entity\Db\ContrainteCursus;
use Application\Provider\Privilege\ParametrePrivileges;
use Application\View\Helper\ContrainteCursus\ContrainteCursusViewHelper;

/**
 * @see ContrainteCursusController::indexAction()
 *
 * @var ContrainteCursus[] $contraintes
 */
$this->headTitle("Contraintes de cursus");
/** @var ContrainteCursusViewHelper $vh */
$vh = $this->administrationContrainteCursus();
$canAdd = $this->isAllowed(ParametrePrivileges::getResourceId(ParametrePrivileges::PARAMETRE_CONTRAINTE_CURSUS_AJOUTER));
$contraintesContradictoires = [];
foreach ($contraintes as $contrainte) {
    if ($contrainte->isContradictoire()) {
        $contraintesContradictoires[] = $contrainte;
    }
}
?>


<h1 class="page-header">
    <span class="icon">
        <i class="fas fa-check-square"></i>
    </span>
    Gestion des contraintes de cursus des étudiants
</h1>


<?php if (!empty($contraintesContradictoires)) : ?>
    <div class="card">
        <div class="card-header card-info">Informations</div>
        <div class="card-body">
            <ul class="list-group list-group-flush">
                <?php /** @var ContrainteCursus $contrainte */
                foreach ($contraintesContradictoires as $contrainte): ?>
                    <li class="list-group-item">
                        <div class="alert alert-warning">
                            La contrainte <?= $contrainte->getLibelle() ?> est en contradiction avec une autre
                        </div>
                    </li>
                <?php endforeach ?>
            </ul>
        </div>
    </div>
<?php endif; ?>


<div class="card mt-3">
    <?php if ($canAdd) : ?>
        <div class="card-header card-sub-header text-end">
            <?= $vh->lienAjouter() ?>
        </div>
    <?php endif; ?>
    <div id="contraintes-content" class="card-body"
         data-url="<?= $this->url(ContrainteCursusController::ROUTE_LISTER, [], [], true) ?>">
        <?= $vh->renderListe($contraintes) ?>
    </div>
</div>

<script type="text/javascript">
    //Rechargement de la page sur event
    $(function () {
        let body = $("body");

        body.on("<?=ContrainteCursusController::EVENT_AJOUTER?> "
            + "<?=ContrainteCursusController::EVENT_MODIFIER?> "
            + "<?=ContrainteCursusController::EVENT_SUPPRIMER?> "
            , function () {//Requis un reload pour gérer l'affichage des contradictio
                window.location.reload()
            });
    })
</script>