<?php

use Application\Controller\Affectation\AffectationController;
use Application\Entity\Db\SessionStage;
use Application\Form\Misc\ConfirmationForm;
use Application\View\Helper\Misc\ConfirmationFormViewHelper;

/**
 * @see AffectationController::calculerAffectationsAction()
 * @var string              $title
 * @var ConfirmationForm    $form
 * @var SessionStage    $sessionStage
 * @var \Application\Entity\Db\ProcedureAffectation    $procedureAffectation
 */

/** @var ConfirmationFormViewHelper $vh */
$vh = $this->confirmation($form)
?>

<div class="card card-primary">
    <h1 class="page-header card-header">
        <span class="fas fa-cogs"></span>
        <?= $title ?>
    </h1>
    <div class="card-body">

        <?php if(!$form->hasBeenConfirmed()) :?>
            <div class='alert alert-warning'>
                <strong>Cette action est irréversible</strong>
                <div>Toute affectation non validée ou pré-validée sera potentiellement modifiée.</div>
            </div>

            <?php //Différent messages selon la dates
            $today = new DateTime();
            if ($sessionStage->getDateDebutStage() <= $today) : ?>
                <div class="card-text alert alert-warning">
                    Le stage est <strong><?= ($sessionStage->getDateFinStage() <= $today) ? "terminée" : "en cours" ?></strong>.
                </div>
            <?php elseif ($sessionStage->getDateFinCommission() <= $today) : ?>
                <div class="card-text alert alert-info">
                    La commission d'affectation est
                    <strong><?= ($sessionStage->getDateFinCommission() <= $today) ? "terminée" : "en cours" ?></strong>.
                </div>
            <?php else : ?>
                <div class="card-text alert alert-info">
                    La commission d'affectation est fixée au <strong><?= $sessionStage->getDateCommission()->format('d/m/Y') ?></strong>.
                </div>
            <?php endif; ?>

        <?php endif; ?>
        <div class="row">
            <div class="col-md-2">
                <strong>Procédure d'affectation</strong>
            </div>
            <div class="col-md-4">
               <?= $procedureAffectation->getLibelle() ?>
            </div>
        </div>

        <?= $vh->render(); ?>
    </div>
</div>

<script>
    $(function () {
        let body = $("body");
        body.off("<?= AffectationController::EVENT_MODIFIER?>", closeModal)
            .one("<?= AffectationController::EVENT_MODIFIER?>", closeModal);
    });
</script>