<?php

use Application\Controller\Convention\ModeleConventionController;
use Application\Form\Convention\Fieldset\ModeleConventionStageFieldset;
use Application\Form\Convention\ModeleConventionStageForm;


/**
 * @see ModeleConventionController::ajouterAction()
 * @see ModeleConventionController::modifierAction()
 *

 * @var ModeleConventionStageForm $form
 * @var ModeleConventionStageFieldset $fieldset
 */

$fe = $this->formErrors();
$fcg = $this->formControlGroup();
$fr = $this->formrow();
$fct = $this->formControlText();
$fieldset = $form->getEntityFieldset();
?>

<nav>
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
        <button class="nav-link active" id="nav-infos"
                data-bs-toggle="tab" data-bs-target="#form-infos"
                type="button"
                role="tab" aria-controls="form-identite"
                aria-selected="true">Informations générales
        </button>
        <button class="nav-link" id="nav-corps"
                data-bs-toggle="tab" data-bs-target="#form-corps"
                type="button"
                role="tab" aria-controls="form-corps"
                aria-selected="false">Corps
        </button>
        <button class="nav-link" id="nav-css"
                data-bs-toggle="tab" data-bs-target="#form-css"
                type="button"
                role="tab" aria-controls="form-css"
                aria-selected="false">CSS
        </button>
        <button class="nav-link" id="nav-terrains"
                data-bs-toggle="tab" data-bs-target="#form-terrains"
                type="button"
                role="tab" aria-controls="form-terrains"
                aria-selected="false">Terrains
        </button>
    </div>
</nav>


<?= $this->form()->openTag($form->prepare()) ?>
<div class="card">
    <div class="card-body">
        <?= $fe($form->prepare(), ModeleConventionStageForm::INVALIDE_ERROR_MESSAGE) ?>
        <?= $fr($fieldset->get($fieldset::ID)) ?>

        <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade show active border-0" id="form-infos"
                 role="tabpanel" aria-labelledby="nav-infos">
                <div class="row">
                    <div class="col-md-6">
                        <?= $fcg($fieldset->get(ModeleConventionStageFieldset::LIBELLE)); ?>
                    </div>
                    <div class="col-md-6">
                        <?= $fcg($fieldset->get(ModeleConventionStageFieldset::CODE)); ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <?= $fct($fieldset->get(ModeleConventionStageFieldset::DESCRIPTION)); ?>
                    </div>
                </div>
            </div>

            <div class="tab-pane fade showb border-0 " id="form-corps"
                 role="tabpanel" aria-labelledby="nav-corps">
                <div class="row">
                    <div class="col-md-12">
                        <?= $fct($fieldset->get(ModeleConventionStageFieldset::CORPS)); ?>
                    </div>
                </div>
            </div>


            <div class="tab-pane fade showb border-0 " id="form-css"
                 role="tabpanel" aria-labelledby="nav-css">
                <div class="row">
                    <div class="col-md-12">
                        <?= $fcg($fieldset->get(ModeleConventionStageFieldset::CSS)); ?>
                    </div>
                </div>
            </div>

            <div class="tab-pane fade showb border-0 " id="form-terrains"
                 role="tabpanel" aria-labelledby="nav-terrains">
                <div class="row">
                    <div class="col-md-6">
                        <?= $fcg($fieldset->get(ModeleConventionStageFieldset::TERRAINS)); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="card-footer">

        <div class="row">
            <div class="col-md-12">
                <?= $fcg($form->get(ModeleConventionStageForm::INPUT_SUBMIT)); ?>
            </div>
        </div>
        <?= $this->formHidden($form->get(ModeleConventionStageForm::CSRF)); ?>
    </div>
</div>


<?= $this->form()->closeTag(); ?>



<?php echo $this->macroInsert() ?>
<script type="text/javascript">

    $(function () {
        $('.selectpicker').selectpicker('render');

        //Empeche de naviguer dans un autre tab-pane que celui du formulaire (a cause de la modal)
        $('#nav_form_modele-convention-stages a').on('click', function (e) {
            e.preventDefault();
            $(this).tab('show')
            return false;
        })

        $('input#<?= $fieldset::DESCRIPTION ?>').addClass('descriptionArea');
        $('input#<?= $fieldset::CORPS ?>').addClass('contenuArea');
        $('input#<?= $fieldset::CSS ?>').addClass('cssArea');

        tinymce.remove();
        tinymce.init({
            selector: '.descriptionArea',
            toolbar: 'newdocument undo redo | bold italic underline | bullist',
            resize: true,
            language: 'fr_FR',
            entity_encoding: "raw",
            plugins: 'lists',
            statusbar: true,
            browser_spellcheck: true,
            branding: false,
            menubar: false,
            body_id: '<?= $fieldset::DESCRIPTION ?>',
            setup: function (editor) {
                editor.on("initEditor", function () {
                    $('#<?= $fieldset::DESCRIPTION ?>.descriptionArea').val(tinymce.get('<?= $fieldset::DESCRIPTION ?>.descriptionArea').getContent());
                });
            }
        });
        tinymce.init({
            selector: '.contenuArea',
            toolbar: 'newdocument undo redo | bold italic underline | bullist | alignleft  aligncenter alignright alignjustify | formatselect | link image  | code',
            block_formats: 'Normal=p;Titre 1=h1;Titre 2=h2;Titre 3=h3',
            resize: true,
            height: "500",
            language: 'fr_FR',
            entity_encoding: "raw",
            forced_root_block: "",
            plugins: 'lists link code',
            paste_as_text: true,
            statusbar: true,
            browser_spellcheck: true,
            branding: false,
            menubar: false,
            body_id: '<?= $fieldset::CORPS ?>',
            setup: function (editor) {
                editor.on("initEditor", function () {
                    $('#<?= $fieldset::CORPS ?>.contenuArea').val(tinymce.get('<?= $fieldset::CORPS ?>.contenuArea').getContent());
                });
            }
        });
    });

    const macros = <?php echo $form->generateMacrosJsonValue() ?>;
    $(function () {
        installMacrosWidgets(macros);
    });
</script>
