<?php

use Application\Controller\Stage\SessionStageController;
use Application\Entity\Db\Parametre;
use Application\Form\Stages\Fieldset\PeriodeStageFieldset;
use Application\Form\Stages\Fieldset\SessionStageFieldset;
use Application\Form\Stages\PeriodeStageForm;
use Application\Form\Stages\SessionStageForm;
use Application\Misc\Util;
use Application\Provider\Tag\TagProvider;
use Application\View\Helper\Parametres\ParametreViewHelper;
use Application\View\Helper\SessionsStages\SessionStageViewHelper;


/**
 * @see SessionStageController::ajouterPeriodeStageAction()
 * @see SessionStageController::modifierPeriodeStageAction()
 * @see SessionStageViewHelper::renderPeriodeStageForm()
 * @var PeriodeStageForm $form
 * @var PeriodeStageFieldset $fieldset
 */

$fe = $this->formErrors();
$fcg = $this->formControlGroup();
$fr = $this->formrow();
$fct = $this->formControlText();
$tagVh =  $this->unicaenTag();

$title = $form->getTitle();
$fieldset = $form->getEntityFieldset();

/** @var ParametreViewHelper $parametreVh */
$parametreVh = $this->parametre();
$dateCalculOrdreAuto = $parametreVh->getParametreService()->getParametreValue(Parametre::DATE_CALCUL_ORDRES_AFFECTATIONS);
$dateChoix = $parametreVh->getParametreService()->getParametreValue(Parametre::DATE_PHASE_CHOIX);
$dateAffectation = $parametreVh->getParametreService()->getParametreValue(Parametre::DATE_PHASE_AFFECTATION);
$dateValidation = $parametreVh->getParametreService()->getParametreValue(Parametre::DATE_PHASE_VALIDATION);
$dateEvaluation = $parametreVh->getParametreService()->getParametreValue(Parametre::DATES_PHASE_EVALUATION);
$dureeChoix = $parametreVh->getParametreService()->getParametreValue(Parametre::DUREE_PHASE_CHOIX);
$dureeStage = $parametreVh->getParametreService()->getParametreValue(Parametre::DUREE_STAGE);
$dureeValidation = $parametreVh->getParametreService()->getParametreValue(Parametre::DUREE_PHASE_VALIDATION);
$dureeEvaluation = $parametreVh->getParametreService()->getParametreValue(Parametre::DUREE_PHASE_EVALUATION);


?>

<div class="fieldset">
    <?= $this->form()->openTag($form->prepare()) ?>

    <div class="row">
        <div class="col-md-4"><?= $fcg($fieldset->get($fieldset::DATE_DEBUT)) ?></div>
        <div class="col-md-4"><?= $fcg($fieldset->get($fieldset::DATE_FIN)) ?></div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?= $fcg($fieldset->get($fieldset::ID)); ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <?= $fr($form->get($form::INPUT_SUBMIT)); ?>
        </div>
    </div>
    <?= $this->formHidden($form->get($form::CSRF)); ?>
    <?= $this->form()->closeTag(); ?>
</div>
