<?php

use Application\Controller\Contact\ContactController;
use Application\Controller\Terrain\TerrainStageController;
use Application\Form\Misc\ImportForm;
use Application\Misc\Util;
use Application\Service\Misc\CSVService;
use Application\Validator\Import\ContactTerrainCsvImportValidator;
use UnicaenApp\View\Helper\Messenger;

/**
 * @see ContactController::importerAction()
 * @var string $title
 * @var ImportForm $form
 */
$fe = $this->formErrors();
$fr = $this->formrow();
$fcg = $this->formControlGroup();
?>

<div class="card card-primary">
    <h1 class="page-header card-header">
        <span class="icon icon-importer"></span>
        <?= $title ?>
    </h1>
    <div class="card-body">
        <div class="fieldset">
            <?= $this->form()->openTag($form->prepare()) ?>
            <?= $fe($form->prepare(), $form::INVALIDE_ERROR_MESSAGE) ?>

            <div class="row">
                <div class="col-md-4">
                    <?= $fcg($form->get($form::INPUT_IMPORT_FILE)); ?>
                </div>
                <div class="col-md-8 text-muted text-small">
                    <ul>
                        <li>Le fichier CSV doit :
                            <ul>
                                <li> utiliser comme séparateur le '<?= CSVService::SEPARATOR ?>'</li>
                                <li> être encodé en utf8</li>
                                <?php  $ob = "<sup title='Champs obligatoire'>*</sup>"; ?>
                                <li> avoir les champs suivants : (<?=$ob?> = Champs obligatoires)<br/>
                                    <?php $h = "";
                                    foreach (ContactTerrainCsvImportValidator::getImportHeader() as $key) {
                                        $obligatoire =  ContactTerrainCsvImportValidator::isChampsObligatoire($key);
                                        $h .= sprintf("<strong><span class='mx-2'>%s %s </span></strong>; ", $key, (($obligatoire) ? $ob : ''));
                                    }
                                    echo $h;
                                    ?>
                            </ul>
                        </li>
                        <li>Les modifications n'impacterons que les futurs stages associés aux terrains.</li>
                        <li>
                            Les champs <strong><?= ContactTerrainCsvImportValidator::HEADER_CODE_CONTACT ?></strong>
                            et <strong><?= ContactTerrainCsvImportValidator::HEADER_CODE_TERRAIN ?></strong>
                            doivent correspondre aux codes des contacts et terrains de stages à associé
                        </li>
                        <li>
                            <strong><?= ContactTerrainCsvImportValidator::HEADER_VISIBLE ?></strong> : Le contact sera
                            il visible par un étudiant ? <span class="mx-3">(Oui / Non)</span>
                        </li>
                        <li>
                            <strong><?= ContactTerrainCsvImportValidator::HEADER_RESPONSABLE ?></strong> : Le contact sera
                            il le responsable des stages ? <span class="mx-3">(Oui / Non)</span>
                        </li>
                        <li>
                            <strong><?= ContactTerrainCsvImportValidator::HEADER_LISTE_ETUDIANTS ?></strong> : Le contact doit-il recevoir par mail la liste des étudiant<?=Util::POINT_MEDIANT ?>s affecté<?=Util::POINT_MEDIANT ?>s ? <span class="mx-3">(Oui / Non)</span>
                        </li>
                        <li>
                            <strong><?= ContactTerrainCsvImportValidator::HEADER_VALIDEUR ?></strong> : Le contact pourra-il
                            valider les stage ? <span class="mx-3">(Oui / Non)</span>
                        </li>
                        <li>
                            <strong><?= ContactTerrainCsvImportValidator::HEADER_CONVENTION ?></strong> : Le contact
                            est-il signataire des conventions de stages ? <span class="mx-3">(Oui / Non)</span>
                        </li>
                        <li>
                            <strong><?= ContactTerrainCsvImportValidator::HEADER_CONVENTION_ORDRE ?></strong> : Ordre
                            parmis les signataires des conventions de stages ? <span class="mx-3">(Oui / Non)</span>
                        </li>
                        <?php //Message éventuelle pour l'import
                        $msg = $this->messenger()->addCurrentMessagesFromFlashMessengerWithNamespace(ContactController::ACTION_IMPORTER . Messenger::NAMESPACED_SEVERITY_SEPARATOR . "*");
                        ?>
                    </ul>
                </div>
            </div>

            <hr/>
            <div class="row">
                <div class="col-md-12">
                    <?= $fcg($form->get($form::INPUT_SUBMIT)); ?>
                </div>
            </div>

            <?php if ($msg && $msg->hasMessages()) : ?>
                <div class="row">
                    <div class="col-md-12">
                        <div>
                            <strong><?= $msg ?></strong>
                        </div>
                    </div>
                </div>
            <?php endif; ?>

            <?= $this->formHidden($form->get($form::CSRF)); ?>
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>

<script>
    $(function () {
        let body = $("body");
        body.off("<?= TerrainStageController::EVENT_IMPORTER?>", closeModal)
            .one("<?= TerrainStageController::EVENT_IMPORTER?>", closeModal);
    })
</script>
