<?php

use Application\Controller\Referentiel\ReferentielPromoController as Controller;
use Application\Entity\Db\ReferentielPromo;
use Application\Provider\Privilege\ReferentielPrivilege;

/**
 * @see ReferentielPromoController::indexAction()
 * @var ReferentielPromo[] $referentielsPromos
 */

$title = "Liste des référentiels de promotions étudiantes";
$this->headTitle($this->translate($title));

/** @var \Application\View\Helper\Referentiel\ReferentielPromoViewHelper $vh */
$vh = $this->referentielPromo();
$canAdd = $vh->hasPrivilege(ReferentielPrivilege::REFERENTIEL_PROMO_AJOUTER);

?>
<h1 class="page-header">
    <span class="icon">
        <i class="fas fa-users"></i>
    </span>
    <?= $title ?>
</h1>


<div class="card mt-3">
    <?php if ($canAdd) : ?>
        <div class="card-header card-sub-header text-end">
            <?= $vh->lienAjouter() ?>
        </div>
    <?php endif; ?>
<div class="card-body" id="referentiels-promos" data-url="<?= $this->url(Controller::ROUTE_LISTER, [], [], true) ?>">
    <?= $vh->renderListe($referentielsPromos) ?>
</div>
</div>

<script type="text/javascript">
    //Rechargement de la page sur event
    $(function () {
        let body = $("body");
        body.on("<?=Controller::EVENT_AJOUTER?> "
            + "<?=Controller::EVENT_MODIFIER?> "
            + "<?=Controller::EVENT_SUPPRIMER?> "
            , function () {
                $("#referentiels-promos").refresh();
            });
    });
</script>