<?php

use Application\Controller\Etudiant\EtudiantController;
use Application\Form\Referentiel\Interfaces\ImportEtudiantsFormInterface;
use Application\View\Helper\Etudiant\EtudiantViewHelper;
use UnicaenApp\View\Helper\Messenger;

/**
 * @see EtudiantController::importerAction()
 * @var string $title
 * @var ImportEtudiantsFormInterface[] $forms
 */
$fe = $this->formErrors();
$fcg = $this->formControlGroup();
$fr = $this->formrow();
/** @var EtudiantViewHelper $vh */
$vh = $this->etudiant();
?>


<h1 class="page-header">
    <span class="icon icon-importer"></span>
    <?= $title ?>
</h1>


<?php
$namespace = EtudiantController::ACTION_IMPORTER . Messenger::NAMESPACED_SEVERITY_SEPARATOR . "*";
$msg = $this->messenger()->addCurrentMessagesFromFlashMessengerWithNamespace($namespace);
?>
<?php if ($msg && $msg->hasMessages()) : ?>
    <div class="row">
        <div class="col-md-12">
            <?= $msg ?>
        </div>
    </div>
<?php endif; ?>

<nav>
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
        <?php foreach ($forms as $form) :
            $actif = $form->isActif();
            $key = $form->getKey();
            $label = $form->getFormLabel();
        ?>
        <button class="nav-link <?= ($actif) ? "active" : "" ?>" id="nav-<?=$key ?>"
                data-bs-toggle="tab" data-bs-target="#pan-<?=$key ?>"
                type="button"
                role="tab" aria-controls="infos"
                aria-selected="<?= ($actif) ? "true" : "false" ?>"> <?= $label ?>
        </button>
        <?php endforeach; ?>
    </div>
</nav>

<div class="card tab-content" id="nav-tabContent">
    <?php foreach ($forms as $form) :
    $actif = $form->isActif();
    $key = $form->getKey();
    ?>
    <div class="tab-pane fade show <?= ($actif) ? "active" : "" ?>" id="pan-<?=$key?>"
         role="tabpanel" aria-labelledby="nav-<?=$key?>">

        <div class="card-body">
            <?= $vh->renderImportForm($form) ?>
        </div>
    </div>
    <?php endforeach; ?>

    <div class="card-footer">
        <div class="row">
            <div class="col-md-12">
                <?= $this->backButton("Liste des étudiants")->backTo($this->url(EtudiantController::ROUTE_INDEX, [], [], true)) ?>
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {
        $('.selectpicker').selectpicker('render');
    })
</script>
