<?php

use Application\Entity\Db\Adresse;
use Application\Entity\Db\Etudiant;
use Application\Provider\EtatType\EtudiantEtatTypeProvider;
use Application\View\Helper\Etudiant\EtudiantViewHelper;

/**
 * @see EtudiantViewHelper::renderInfos()
 * @var Etudiant $etudiant
 */
/** @var EtudiantViewHelper $vh */
$vh = $this->etudiant($etudiant);
/** @var Adresse $adresse */
$adresse = $etudiant->getAdresse();
?>


<div class="row row-cols-1 row-cols-md-2">
    <div class="col">
        <div class="card h-100">
            <div class="card-header">
                Identité
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-4">
                        <strong>Nom</strong>
                    </div>
                    <div class="col-md-8">
                        <?= $etudiant->getNom() ?>
                    </div>
                    <div class="col-md-4">
                        <strong>Prénom</strong>
                    </div>
                    <div class="col-md-8">
                        <?= $etudiant->getPrenom() ?>
                    </div>
                    <div class="col-md-4">
                        <strong>Date de naissance</strong>
                    </div>
                    <div class="col-md-8">
                        <?= ($etudiant->getDateNaissance()) ? $etudiant->getDateNaissance()->format('d/m/Y') : "Information non renseignée" ?>
                    </div>

                    <div class="col-md-4">
                        <strong>Numéro étudiant</strong>
                    </div>
                    <div class="col-md-8">
                        <?= $etudiant->getNumEtu() ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="card h-100">
            <div class="card-header">
                Profil
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-4">
                        <strong>Compte</strong>
                    </div>
                    <div class="col-md-8">
                        <?php
                        $user = $etudiant->getUser();
                        echo match (true) {
                            !isset($user) => "<span class='badge badge-muted'>Inactif</span>",
                            !$user->getState() => sprintf("%s <span class='mx-3 badge badge-danger'>Suspendu</span>", $user->getUsername()),
                            default => sprintf("%s <span class='mx-3 badge badge-success'>Actif</span>", $user->getUsername()),
                        };
                        ?>
                    </div>
                    <div class="col-md-4">
                        <strong>Email</strong>
                    </div>
                    <div class="col-md-8">
                        <?= $etudiant->getEmail() ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row row-cols-1 row-cols-md-2">
    <div class="col">
        <div class="card h-100">
            <div class="card-header">
                Adresse
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-4">
                        <strong>Adresse</strong>
                    </div>
                    <div class="col-md-8">
                        <?= (isset($adresse) && $adresse->getAdresse() != "") ? $adresse->getAdresse() : "<span class='text-muted text-small'>Non renseignée</span>" ?>
                    </div>
                    <div class="col-md-4">
                        <strong>Complément</strong>
                    </div>
                    <div class="col-md-8">
                        <?= (isset($adresse) && $adresse->getComplement() != "") ? $adresse->getComplement() : "<span class='text-muted text-small'>Non renseigné</span>" ?>
                    </div>
                    <div class="col-md-4">
                        <strong>Code postal</strong>
                    </div>
                    <div class="col-md-8">
                        <?= (isset($adresse) && $adresse->getCodePostal() != "") ? $adresse->getCodePostal() : "<span class='text-muted text-small'>Non renseigné</span>" ?>
                    </div>
                    <div class="col-md-4">
                        <strong>Ville</strong>
                    </div>
                    <div class="col-md-8">
                        <?= (isset($adresse) && $adresse->getVille() != "") ? $adresse->getVille() : "<span class='text-muted text-small'>Non renseignée</span>" ?>
                    </div>
                    <div class="col-md-4">
                        <strong>Cedex</strong>
                    </div>
                    <div class="col-md-8">
                        <?= (isset($adresse) && $adresse->getCedex() != "") ? $adresse->getCedex() : "<span class='text-muted text-small'>Non renseigné</span>" ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <?php
            $etat = $etudiant->getEtatActif();
            $bg = match (true) {
                $etudiant->hasEtatEnErreur() => "card-danger",
                $etudiant->hasEtatEnAlerte() => "card-warning",
                $etudiant->hasEtatCursusValide() => "card-success",
                $etudiant->hasEtatCursusNonValide() => "card-danger",
                $etudiant->hasEtatEnDispo() => "card-muted",
                default => "card-primary",
            }
        ?>

        <div class="card h-100 <?= $bg ?>">
            <div class="card-header">
                État du cursus
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                    <?= $this->etatinstance($etat, ['display-categorie' => false, 'display-libelle'=> true, 'unknown-type-libelle' => "Indéterminée"], ); ?>
                    </div>
                </div>
                <?php if(isset($etat) && $etat->getInfos() != "") : ?>
                <div class="row">
                    <div class="col-md-12"><strong>Informations</strong></div>
                    <div class="col-md-12">
                    <?= $etat->getInfos(); ?>
                    </div>
                </div>
                <?php endif;?>
            </div>
        </div>
    </div>
</div>