<?php

use Application\Controller\Convention\ModeleConventionController;
use Application\Form\Convention\ModeleConventionStageForm;
use Application\View\Helper\Convention\ModeleConventionViewHelper;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @see ModeleConventionController::modifierAction()
 *

 * @var string $title
 * @var ModeleConventionStageForm $form
 */

/** @var ModeleConventionViewHelper $vh */
$vh = $this->modeleConvention();
?>

<div class="card card-primary">
    <h1 class="page-header card-header">
        <span class="icon icon-modifier"></span>
        <?= $title ?>
    </h1>
    <div class="card-body">
        <?= $vh->renderForm($form); ?>
    </div>
</div>

<script>
    $(function () {
        let body = $("body");
        body.off("<?= ModeleConventionController::EVENT_MODIFIER ?>", closeModal)
            .one("<?= ModeleConventionController::EVENT_MODIFIER ?>", closeModal);
    })
</script>