<?php

use Application\Controller\Groupe\GroupeController;
use Application\Form\Misc\ConfirmationForm;
use Application\View\Helper\Misc\ConfirmationFormViewHelper;
use Laminas\View\Renderer\PhpRenderer;

/**
 * @see GroupeController::supprimerAction()
 *

 * @var string $title
 * @var ConfirmationForm $form
 */

/** @var ConfirmationFormViewHelper $vh */
$vh = $this->confirmation($form)
?>

<div class="card card-danger">
    <h1 class="page-header card-header">
        <span class="icon icon-supprimer"></span>
        <?= $title ?>
    </h1>
    <div class="card-body">

        <?php if(!$form->hasBeenConfirmed()) :?>
        <div class='alert alert-warning'>
            <strong>Cette action est irréversible</strong>
            <div>Supprimer le groupe implique la suppressions <strong>définitivement</strong> des stages et autres informations liées.</div>
        </div>
        <?php endif; ?>
        <?= $vh->render(); ?>
    </div>
</div>

<script>
    $(function () {
        let body = $("body");
        body.off("<?= GroupeController::EVENT_SUPPRIMER?>", closeModal)
            .one("<?= GroupeController::EVENT_SUPPRIMER?>", closeModal);
    });
</script>
