<?php

use Application\Entity\Db\SessionStage;
use Application\Entity\Db\TerrainStage;
use Application\View\Helper\SessionsStages\SessionStageViewHelper;


/**
 * @see SessionStageViewHelper::renderPlacesTerrains()
 * @var SessionStage $sessionStage
 */

$nbPlacesTotal = $sessionStage->getNbPlacesOuvertesTotal();
$stages = $sessionStage->getStages()->toArray();
$nbStages = sizeof($stages);
$tableId = "session_". $sessionStage->getId() ."_terrains" ;
$vh = $this->sessionStage($sessionStage);
?>
    <div class="card">
        <div class="card-header">Informations</div>
        <div class="card-body">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                <div class="row">
                    <div class="col-md-3">
                        <strong>Nombre de place(s) ouverte(s)</strong>
                    </div>
                    <div class="col-md-1">
                        <?= $nbPlacesTotal ?>
                        <span class="mx-1 fas fa-house-medical"></span>
                    </div>
                    <div class="col-md-3">
                        <strong>Nombre d'étudiant(s)</strong>
                    </div>
                    <div class="col-md-1">
                        <?= $nbStages ?>
                        <span class="mx-1 fas fa-users"></span>
                    </div>
                </div>
                </li>

            <li class="list-group-item">
                Le nombre de place(s) ouverte(s) est donné sous la forme
                <span class="badge badge-light-info">Nombre de stage(s) affecté(s) / Nombre de place(s) ouverte(s)</span>
                <br /> Cliquer dessus pour afficher plus d'informations sur le nombre de place(s).
            </li>
        </div>
    </div>

    <div class="card mt-3">
        <div class="card-header">Place(s) ouverte(s) par terrain de stages</div>
        <div class="card-body">
            <table id="<?= $tableId ?>" class="table table-hover table-condensed">
                <thead>
                <tr>
                    <th class="hidden">Type de terrain</th>
                    <th class="col-md-4" data-type="num">Catégorie</th>
                    <th class="col-md-4">Terrain</th>
                    <th class="col-md-1 no-search text-center" data-type="num">Places ouvertes</th>
                    <th class="col-md-1 no-search" data-type="num">Demandes</th>
                </tr>
                </thead>
                <tbody>
                <?php /** @var TerrainStage $terrain */
                foreach ($sessionStage->getTerrainsStages() as $terrain) :
                    $categorie = $terrain->getCategorieStage();
                    $nbPlaces = $sessionStage->getNbPlacesOuvertes($terrain);


                    $actuel = $sessionStage->getNbPlacesOuvertes($terrain);
                    $min = $terrain->getMinPlace();
                    $ideal = $terrain->getIdealPlace();
                    $max = $terrain->getMaxPlace();
                    $terrainLinker = $sessionStage->getTerrainLinkFor($terrain);
                    $reco = $terrainLinker->getNbPlacesRecommandees();
                    $nbPlacesPreAffectees = $terrainLinker->getNbPlacesPreAffectees();
                    $nbPlacesAffectees = $terrainLinker->getNbPlacesAffectees();

                    $niveauDemande = $sessionStage->getNiveauDemande($terrain);
                    ?>
                    <tr>
                        <td class="hidden">Terrains <?=($terrain->isTerrainPrincipal()) ? "Principaux" : "Secondaires" ?></td>
                        <td class="" data-order="<?= $categorie->getOrdre()?>">
                            <?= $categorie->getLibelle() ?>
                        </td>
                        <td> <?= $terrain->getLibelle() ?></td>
                        <td class="text-center"
                            data-order="<?= $nbPlaces ?>"
                        >
                            <?php $badgeClass = "";
                                switch (true){
                                    case ($nbPlacesPreAffectees == $nbPlaces && $nbPlaces==0) :
                                        $badgeClass = "badge-muted";
                                    break;
                                    case ($nbPlacesPreAffectees < $nbPlaces ) :
                                        $badgeClass = "badge-light-info";
                                    break;
                                    case ($nbPlacesPreAffectees == $nbPlaces ) :
                                        $badgeClass = "badge-success";
                                    break;
                                    case ($nbPlacesPreAffectees > $nbPlaces ) :
                                        $badgeClass = "badge-warning";
                                    break;
                                }
                            ?>

                            <a class="mx-1 pointer-hover" data-bs-toggle="dropdown" aria-expanded="false">
                                <span class='me-1 badge <?= $badgeClass?>'><?= $nbPlacesPreAffectees ?> / <?= $nbPlaces ?></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li class="dropdown-item"
                                ><span class='me-1 badge badge-primary'><?= $actuel ?></span>
                                    Nombre de place(s) actuellement ouverte(s)
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li class="dropdown-item"
                                ><span class='me-1 badge badge-secondary'><?= $min ?></span>
                                    Capacité minimale du terrain
                                </li>
                                <li class="dropdown-item"
                                ><span class='me-1 badge badge-light-success'><?= $ideal ?></span>
                                    Capacité idéale du terrain
                                </li>
                                <li class="dropdown-item"
                                ><span class='me-1 badge badge-light-danger'><?= $max ?></span>
                                    Capacité maximale du terrain
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li class="dropdown-item"
                                ><span class='me-1 badge badge-success'><?= $reco ?></span>
                                    Nombre de place(s) recommandée(s)
                                </li>
                                <li class="dropdown-item"
                                ><span class='me-1 badge badge-light-warning'><?= $nbPlacesPreAffectees ?></span>
                                    Nombre de place(s) pré-affectée(s) + affectée(s)
                                </li>
                                <li class="dropdown-item"
                                ><span class='me-1 badge badge-warning'><?= $nbPlacesAffectees ?></span>
                                    Nombre de place(s) affectée(s)
                                </li>
                            </ul>
                        </td>
                        <td class="" data-order="<?= (isset($niveauDemande))? $niveauDemande->getOrdre() : PHP_INT_MAX ?>"> <?= $vh->getDemandesTerrainsInfos($terrain) ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>

        </div>
    </div>


    <script type="text/javascript">
        $(function () {
            let options = generateDataTableSetings({
                    order: [[1, 'asc'], [2, 'asc']],
                    "lengthMenu": [[50, 100, 250, -1], [50, 100, 250, "Tous"]],
                    "orderFixed": {
                        "pre": [ 0, 'asc' ],
                    },
                    rowGroup: {
                        dataSrc: 0
                    },
                }
            );
            let tableInstance = $("#<?= $tableId ?>").DataTable(options);
        });
    </script>
