<?php

use Application\Controller\Stage\SessionStageController;
use Application\Entity\Db\SessionStage;
use Application\Provider\Misc\Icone;
use Application\Provider\Tag\TagProvider;
use Application\View\Helper\SessionsStages\SessionStageViewHelper;
use UnicaenTag\View\Helper\TagViewHelper;

/**
 * @see SessionStageViewHelper::renderDates()
 * @var SessionStage $sessionStage
 * @var Boolean $vueEtudiante
 */

/** @var TagViewHelper $tagVh */
$tagVh = $this->unicaenTag();
if(!isset($vueEtudiante)){$vueEtudiante = false;}

/** @var SessionStageViewHelper $vh */
$vh = $this->sessionStage($sessionStage);
$canEdit = (!$vueEtudiante)
    && $sessionStage->hasMultiplesPeriodesStage() &&
    $vh->actionAllowed(SessionStageController::ACTION_MODIFIER);


//Background selon les dates
$today = new DateTime();
$bgDateCalculOrdre = ($sessionStage->getDateCalculOrdresAffectations() <= $today && $today <= $sessionStage->getDateFinCalculOrdresAffectations())
    ? "bg-light-success" : (($sessionStage->getDateFinCalculOrdresAffectations() < $today) ? "bg-muted" : "");
$bgDateChoix = ($sessionStage->getDateDebutChoix() <= $today && $today <= $sessionStage->getDateFinChoix())
    ? "bg-light-success" : (($sessionStage->getDateFinChoix() < $today) ? "bg-muted" : "");
$bgDateCommission = ($sessionStage->getDateCommission() <= $today && $today <= $sessionStage->getDateFinCommission())
    ? "bg-light-success" : (($sessionStage->getDateFinCommission() < $today) ? "bg-muted" : "");
$bgDateStage = ($sessionStage->getDateDebutStage() <= $today && $today <= $sessionStage->getDateFinStage())
    ? "bg-light-success" : (($sessionStage->getDateFinStage() < $today) ? "bg-muted" : "");
$bgDateValidation = ($sessionStage->getDateDebutValidation() <= $today && $today <= $sessionStage->getDateFinValidation())
    ? "bg-light-success" : (($sessionStage->getDateFinValidation() < $today) ? "bg-muted" : "");
$bgDateEvaluation = ($sessionStage->getDateDebutEvaluation() <= $today && $today <= $sessionStage->getDateFinEvaluation())
    ? "bg-light-success" : (($sessionStage->getDateFinEvaluation() < $today) ? "bg-muted" : "");


$periodesStages = $sessionStage->getDatesPeriodesStages();

?>
<div class="row">
<div class="col-md-12">
        <table class='table table-hover table-condensed mt-1'>
            <thead>
            <tr>
                <th class="col-md-8">Date</th>
                <th class="col-md-2">Début</th>
                <th class="col-md-2">Fin</th>
            </tr>
            </thead>
            <tbody>
            <?php if(!$vueEtudiante) :?>
            <tr class="<?=$bgDateCalculOrdre ?>">
                <td>Calcul automatique des ordres d'affectations</td>
                <td>
                    <?= ($sessionStage->getDateCalculOrdresAffectations()) ? $sessionStage->getDateCalculOrdresAffectations()->format('d/m/Y') : "Date indéterminée"?>
                </td>
                <td></td>
            </tr>
            <?php endif; ?>
            <tr class="<?=$bgDateChoix ?>">
                <td>Procédure de choix</td>
                <td><?=$sessionStage->getDateDebutChoix()->format('d/m/Y')?></td>
                <td><?=$sessionStage->getDateFinChoix()->format('d/m/Y')?></td>
            </tr>
            <tr class="<?=$bgDateCommission ?>">
                <td>Commission d'affectation des stages</td>
                <td><?=$sessionStage->getDateCommission()->format('d/m/Y')?></td>
                <td></td>
            </tr>
            <tr class="<?=$bgDateStage ?>">
                <td>Stage
                    <?php if($sessionStage->hasMultiplesPeriodesStage()):?>
                        <?php if(empty($periodesStages) && (!$vueEtudiante)):?>
                            <div class="alert alert-warning">
                                La session de stage est taguée <?= $tagVh->renderTag(TagProvider::SESSION_MUlTIPLES_PERIODES,  ['display-libelle' => true]); ?>, mais les périodes effectives de stages ne sont pas définies.
                            </div>
                        <?php elseif(!empty($periodesStages)) :?>
                            <div class="text-small">Périodes de stages effectives</div>
                            <?php foreach($periodesStages as $periode):
                                $vh->setPeriodeStage($periode);
                                ?>
                                <div class="text-small">
                                    <span class="ms-3 <?= Icone::FA_ARROW_RIGHT ?>"></span>
                                    <span class="mx-1">du</span> <span class="mx-1"><?= $periode->getDebut()->format('d/m/Y') ?></span>
                                    <span class="mx-1">au</span> <span class="mx-1"><?= $periode->getFin()->format('d/m/Y') ?></span>
                                    <?= $vh->lienModifierPeriode(Icone::render(Icone::MODIFIER),['class' => 'mx-1 text-primary ajax-modal']); ?>
                                    <?= $vh->lienSupprimerPeriode(Icone::render(Icone::SUPPRIMER),['class' => 'mx-1 text-danger ajax-modal']); ?>
                                </div>
                            <?php endforeach; ?>
                        <?php endif; ?>
                        <?php if($canEdit) :?>
                            <div class="text-small">
                            <?= $vh->lienAjouterPeriode(Icone::render(Icone::AJOUTER). "Ajouter une période de stage", ['class' => 'mx-3 text-success ajax-modal']) ?>
                            </div>
                        <?php endif;?>
                    <?php endif;?>
                </td>
                <td><?=$sessionStage->getDateDebutStage()->format('d/m/Y')?></td>
                <td><?=$sessionStage->getDateFinStage()->format('d/m/Y')?></td>
            </tr>

            <tr class="<?=$bgDateValidation ?>">
                <td>Phase de validation du stage</td>
                <td><?=$sessionStage->getDateDebutValidation()->format('d/m/Y')?></td>
                <td><?=$sessionStage->getDateFinValidation()->format('d/m/Y')?></td>
            </tr>
            <?php if(!$vueEtudiante) : //TODO : a dévelloper?>
            <tr class="<?=$bgDateEvaluation ?>">
                <td>Phase d'évaluation du stage</td>
                <td><?=$sessionStage->getDateDebutEvaluation()->format('d/m/Y')?></td>
                <td><?=$sessionStage->getDateFinEvaluation()->format('d/m/Y')?></td>
            </tr>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>
