<?php

use Application\Entity\Db\AffectationStage;
use Application\Provider\Misc\Icone;
use Application\Provider\Privilege\StagePrivileges;
use Application\View\Helper\Affectation\AffectationViewHelper;


/**
 * @see AffectationViewHelper::renderListe()
 * @var AffectationStage[] $affectationsStages
 */

$tableId = $tableId = "liste-affectations-stages";
/** @var AffectationViewHelper $vh */
$vh = $this->affectation();
$evh = $this->etudiant();
$canSeeAffectation = $vh->hasPrivilege(StagePrivileges::AFFECTATION_AFFICHER);
$today = new DateTime();
?>

<div class="row">
    <div class="col-md-12">

        <table id="<?= $tableId ?>" class="table table-hover table-condensed">
            <thead>
            <tr>
                <th class="col-md-1 no-search" data-type="num">Ordre</th>
                <th class="col-md-3">Étudiant</th>
                <th class="col-md-3">Terrain</th>
                <th class="col-md-4 no-search" data-type="num">État</th>
                <?php if($canSeeAffectation): ?>
                <th class="col-md-1 text-end no-search" data-type="num">Actions</th>
                <?php endif; ?>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($affectationsStages as $affectation):
                $vh->setAffectationStage($affectation);
                $session = $affectation->getSessionStage();
                $vh->setSessionStage($session);
                $stage = $affectation->getStage();
                $etudiant = $affectation->getEtudiant();
                $evh->setEtudiant($etudiant);
                $terrain = ($affectation) ? $affectation->getTerrainStage() : null;
                $terrainSecondaire = ($affectation) ? $affectation->getTerrainStageSecondaire() : null;
                $categorie = ($terrain) ? $terrain->getCategorieStage() : null;
                $categorieSecondaire = ($terrainSecondaire) ? $terrainSecondaire->getCategorieStage() : null;

                $etat = $affectation->getEtatActif();
                $bg = match (true) {
                    $affectation->hasEtatFutur(),
                    $affectation->hasEtatEnDisponibilite(),
                    $affectation->hasEtatStageNonEffectue()
                        => "table-muted",
                    $affectation->hasEtatNonAffecte(),
                    $affectation->hasEtatEnCours()
                    => "",
                    $affectation->hasEtatProposition()
                        => "table-info",
                    $affectation->hasEtatPreValidee()
                        => "table-primary",
                    $affectation->hasEtatValidee()
                        => "table-success",
                    $affectation->hasEtatEnRetard(),
                    $affectation->hasEtatEnAlerte()
                        => "table-warning",
                    $affectation->hasEtatEnErreur()
                        => "table-danger",
                    default => "table-danger"
                };
            ?>
                <tr class="<?= $bg ?>">
                    <td class="" data-order="<?=($stage->getOrdreAffectation()) ?? PHP_INT_MAX ?>">
                        <?= ($stage->getOrdreAffectation()) ?? "<span class='text-muted'>-</span>" ?>
                    </td>
                    <td data-order="<?= $etudiant->getNom() ?> <?= $etudiant->getPrenom() ?> <?= $etudiant->getNumEtu() ?>"
                        data-filter="<?= $etudiant->getNom() ?> <?= $etudiant->getPrenom() ?> <?= $etudiant->getNumEtu() ?>"
                    >
                        <?= $etudiant->getNom() ?> <?= $etudiant->getPrenom() ?> (<?= $evh->lienAfficher()?>)
                    </td>
                    <td data-order="<?= ($terrain) ? $categorie->getLibelle()." ".$terrain->getLibelle() :
                        (($terrainSecondaire) ? $categorieSecondaire->getLibelle()." ".$terrainSecondaire->getLibelle() : '')
                    ?>"
                        data-filter="
                        <?= isset($terrain) ? $terrain->getLibelle() : ""?>
                        <?= isset($terrainSecondaire) ? $terrainSecondaire->getLibelle() : ""?>
                        <?= isset($categorie) ? $categorie->getAcronyme() : ""?>
                        <?= isset($categorieSecondaire) ? $categorieSecondaire->getAcronyme() : ""?>
                    " >
                        <?php if(!isset($terrain)) : ?>
                            <span class="text-muted">Non définie</span>
                        <?php  else : ?>
                            <div><?= $terrain->getLibelle()?> (<?=$categorie->getAcronyme()?>)</div>
                        <?php endif; ?>
                        <?php if($terrainSecondaire) :?>
                            <div class="px-3 text-small"> et <?= $terrainSecondaire->getLibelle()?> (<?=$categorieSecondaire->getAcronyme()?>)</div>
                        <?php endif ?>
                    </td>
                    <td class="" data-order="<?= ($etat) ? ($etat->getType()->getOrdre()) : PHP_INT_MIN ?>"
                        style="color:<?=  (isset($etat)) ? $etat->getType()->getCouleur() : "" ?>"
                    >
                        <span class="<?= (isset($etat)) ? $etat->getType()->getIcone() : "fa fa-question" ?>"></span>
                        <?= (isset($etat)) ? $etat->getTypeLibelle() : "Indéterminé" ?>

                        <?php if($stage->getDateFinChoix() < $today && $affectation->hasPreferencesNonRepresentative()) :?>
                            <div class="text-small">Préférences non-représentatives</div>
                            <?php if($affectation->hasNoPreferences()) :?>
                                <div class="text-small text-danger">Aucune préférence définie</div>
                            <?php endif; ?>
                        <?php endif; ?>
                    </td>
                    <?php if($canSeeAffectation) : ?>
                        <td class="text-end">
                            <?= $vh->lienAfficher(ICONE::AFFICHER, ['class' => 'text-primary ajax-modal']) ?>
                        </td>
                    <?php endif; ?>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        let options = generateDataTableSetings(
            {
                stateSave: true,
                retrieve: true,
                "order": [[0, "asc"]],
                "lengthMenu": [[50, 100, 250, -1], [50, 100, 250, "Tous"]],
            }
        );
        let tableInstance = $("#<?= $tableId ?>").DataTable(options);
    });
</script>
