<?php

use Application\Controller\Parametre\ParametreCoutAffectationController;
use Application\Form\Parametre\ParametreCoutAffectationForm;
use Application\View\Helper\Parametres\ParametreCoutAffectationViewHelper;

/**
 * @see ParametreCoutAffectationController::modifierAction()
 * @var string $title
 * @var ParametreCoutAffectationForm $form
 */

/** @var ParametreCoutAffectationViewHelper $vh */
$vh = $this->parametreCoutAffectation();
?>
<div class="card card-primary">
    <h1 class="page-header card-header">
        <span class="icon icon-modifier"></span>
        <?= $title ?>
    </h1>
    <div class="card-body">
        <?= $vh()->renderForm($form); ?>
    </div>
</div>

<script>
    $(function () {
        let body = $("body");
        body.off("<?= ParametreCoutAffectationController::EVENT_MODIFIER?>", closeModal)
            .one("<?= ParametreCoutAffectationController::EVENT_MODIFIER?>", closeModal);
    })
</script>