<?php

use Application\Controller\Affectation\ProcedureAffectationController  as Controller;
use Application\View\Helper\Affectation\ProcedureAffectationViewHelper;

/**
 * @see ProcedureAffectationController::indexAction()
 *
 * @var \Application\Entity\Db\ProcedureAffectation[] $proceduresAffectations
 */
$this->headTitle("Les procédures d'affectations");

/** @var ProcedureAffectationViewHelper $vh */
$vh = $this->procedureAffectation();
?>


<h1 class="page-header">
    <span class="icon">
        <i class="fas fa-cogs"></i>
    </span>
    Gestions des procédures d'affectations
</h1>


<div class="card mt-3">
    <div class="card-body" id="liste-faq" data-url="<?= $this->url(Controller::ROUTE_LISTER, [], [], true) ?>">
        <?= $vh->renderListe($proceduresAffectations) ?>
    </div>
</div>

<script type="text/javascript">
    //Rechargement de la page sur event
    $(function () {
        let body = $("body");
        body.on("<?=Controller::EVENT_MODIFIER?> "
            , function () {
                $("#liste-procedure").refresh();
            });
    });
</script>