<?php

use Application\Controller\Terrain\TerrainStageController;
use Application\Entity\Db\TerrainStage;
use Application\Provider\Misc\Icone;
use Application\View\Helper\Terrains\TerrainStageViewHelper;

/**
 * @see TerrainStageController::listerAction()

 * @var TerrainStage[] $terrainsStages
 */

$tableId = "liste-terrains-stages";

/** @var TerrainStageViewHelper $vh */
$vh = $this->terrainStage();
?>


<div class="row">
    <div class="col-md-12">
        <table id="<?= $tableId ?>" class="table table-hover table-condensed">
            <thead>
            <tr>
                <th class="hidden">Catégorie</th>
                <th class="hidden no-search" data-type="num"></th>
                <th class="col-md-2">Code</th>
                <th class="col-md-7">Libellé</th>
                <th class="col-md-2 no-search" data-type="num">Etat</th>
                <th class="col-md-1 text-end no-sort no-search">Actions</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($terrainsStages as $terrain):
                $vh->setTerrainStage($terrain); ?>
                <tr class="<?=(!$terrain->isActif()) ? "bg-muted": "" ?> <?=($terrain->isTerrainPrincipal()) ? "cat-principale" : "cat-secondaire" ?>">
                    <td class="hidden">
                        <?= $terrain->getCategorieStage()->getLibelle() ?>
                        <?=($terrain->isTerrainSecondaire()) ? "<span class='text-small'>(Terrains secondaires)</span>" : "" ?></td>
                    <td class="hidden" data-order="<?= ($terrain->getCategorieStage()->isCategoriePrincipale() ? 0 : 10000) + $terrain->getCategorieStage()->getOrdre() ?>"> </td>
                    <td class=""><?= $terrain->getCode() ?></td>
                    <td><?= $terrain->getLibelle() ?></td>
                    <td class="" data-order="<?= (($terrain->isHorsSubdivision()) ? 1 : 0) + (($terrain->isActif()) ? 0 : 1 )*10  ?> ">
                        <?php if($terrain->isHorsSubdivision()) :?>
                            <div class="text-small text-muted">Hors Subdivision</div>
                        <?php endif;?>
                        <?php if(!$terrain->isActif()) :?>
                            <div class="text-small text-muted">Désactivé</div>
                        <?php endif;?>
                    </td>
                    <td class="text-end">
                        <?= $vh->lienAfficher(Icone::render(Icone::AFFICHER), ["class"=>"text-primary"]) ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">
    let body = $("body");

    body.on("toggle-cat-principale", function (){
        $("#<?= $tableId ?> .cat-principale").toggleClass("hidden");
    });
    body.on("toggle-cat-secondaire", function (){
        $("#<?= $tableId ?> .cat-secondaire").toggleClass("hidden");
    });

    $(function () {
        let options = generateDataTableSetings(
            {
                "order": [[4, "asc"]],
                "lengthMenu": [[10, 50, 100, 250, -1], [10, 50, 100, 250, "Tous"]],
                "orderFixed": {
                    "pre": [ 1, 'asc' ],
                },
                rowGroup: {
                    dataSrc: 0
                }
            }
        );
        $("#<?= $tableId ?>").DataTable(options);
    });
</script>